config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only:[:new, :create, :show]
  resources :contracts, only:[:new,:create,:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
end


#jealynt_f
#evelynt.f

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/contract.rb
# == Schema Information
#
# Table name: contracts
#
#  id             :integer          not null, primary key
#  place          :string
#  name           :string
#  nacionality    :string
#  profession     :string
#  academy_degree :string
#  university     :string
#  departament    :string
#  dpi            :string
#  age            :integer
#  marital_status :string
#  email          :string
#  phone          :string
#  body           :text
#  confirmation   :boolean          default(TRUE)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Contract < ApplicationRecord
    validates :place, presence: true
    validates :email, presence: true
    validates :phone, presence: true
    validates :name, presence: true
    validates :confirmation, presence: true
    validates :age, presence: true
    validates :dpi, presence: true
    validates :departament, presence: true
    validates :academy_degree, presence: true
    validates :nacionality, presence: true
    validates :university, presence: true

    #after_create :send_mail

    def send_mail
        ContractMailer.new_contract_mail(self).deliver_now
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :phone, :email, :body)
    end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]

  # GET /contracts
  # GET /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, notice: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contract_params
      params.require(:contract).permit(:place, :name, :nacionality, :profession, :academy_degree, :university, :departament, :dpi, :age, :marital_status, :email, :phone, :confirmation)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label 'Nombre completo' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label 'Número de teléfono' %>
    <%= form.number_field :phone, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label 'Escribe tu consulta aquí' %>
    <%= form.text_area :body, class: 'form-control', rows:3 %>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= contact.body %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<div class="container h-100">
    <div class="row justify-content-center h-100 card">
        <h1 class="text-center top-space">Contáctanos</h1>
        <div class="col-xs-12 col-sm-10 col-md-10 align-self-center mt-3">
            <%= render 'form', contact: @contact, class: 'mb-3' %>
            <%= link_to "Volver al inicio", root_path , class: "" %>
        </div>
    </div>
</div>

app/views/contacts/show.html.erb
<div class="container">
  <div class="row justify-content-center h-100 card">
    <div class="col-xs-12 col-sm-10 col-md-8 align-self-center">
      <h1>Gracias por contactarnos</h1>
      <p>En breve nos comunicaremos con usted</p>
      <%= link_to 'Volver al inicio', root_path, class: 'btn btn-outline-success' %>
    </div>
  </div>
</div>

app/views/contracts/edit.html.erb
<h1>Editing Contract</h1>

<%= render 'form', contract: @contract %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contracts</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Name</th>
      <th>Nacionality</th>
      <th>Profession</th>
      <th>Academy degree</th>
      <th>University</th>
      <th>Departament</th>
      <th>Dpi</th>
      <th>Age</th>
      <th>Marital status</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= contract.place %></td>
        <td><%= contract.name %></td>
        <td><%= contract.nacionality %></td>
        <td><%= contract.profession %></td>
        <td><%= contract.academy_degree %></td>
        <td><%= contract.university %></td>
        <td><%= contract.departament %></td>
        <td><%= contract.dpi %></td>
        <td><%= contract.age %></td>
        <td><%= contract.marital_status %></td>
        <td><%= contract.email %></td>
        <td><%= contract.phone %></td>
        <td><%= link_to 'Show', contract %></td>
        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
        <td><%= link_to 'Destroy', contract, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_contract_path %>

app/views/contracts/new.html.erb
<div class="container h-100">
    <div class="row justify-content-center h-100 card">
        <h1 class="text-center top-space">Contrato para profesionales</h1>
        <div class="col-xs-12 col-sm-10 col-md-10 align-self-center mt-3">
            <%= render 'form', contract: @contract, class: 'mb-3' %>
        </div>
    </div>
</div>

app/views/contracts/show.html.erb
<div class="container">
  <div class="row justify-content-center h-100 card">
    <div class="col-xs-12 col-sm-10 col-md-8 align-self-center">
      <h1>Contrato enviado con éxito</h1>
      <p>Su contrato ha sido enviado con éxito</p>
      <%= link_to 'Volver al inicio', root_path, class: 'btn btn-outline-success' %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="dropdown ml-4">
  <button class="btn radius--btn red text-white p-3 bold dropdown-toggle btn-lg" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Asistencia Especializada
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <%= link_to "Contáctanos", new_contact_path , class: "dropdown-item bold" %>
    <a class="dropdown-item" href="#">Abogados (Entidad a cargo: Legal Assistance Latinoamérica)</a>
    <a class="dropdown-item" href="#">Administración de Empresas</a>
	<div class="dropdown-divider"></div>
    <a class="dropdown-item bold" href="#">Derecho:</a>
    <a class="dropdown-item" href="#">Derecho Administrativo</a>
    <a class="dropdown-item" href="#">Derecho Ambiental</a>
    <a class="dropdown-item" href="#">Derecho Civil</a>
    <a class="dropdown-item" href="#">Derecho Constitucional</a>
    <a class="dropdown-item" href="#">Derecho Laboral</a>
    <a class="dropdown-item" href="#">Derecho mercantil</a>
    <a class="dropdown-item" href="#">Derecho Penal</a>
    <a class="dropdown-item" href="#">Derecho Tributario</a>
    <a class="dropdown-item" href="#">otros</a>
	<div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Antropología</a>
    <a class="dropdown-item" href="#">Auditoría</a>
    <a class="dropdown-item" href="#">Biología</a>
    <a class="dropdown-item" href="#">Comunicaciones</a>
    <a class="dropdown-item" href="#">Económicas</a>
    <a class="dropdown-item" href="#">Finanzas</a>
	<div class="dropdown-divider"></div>
    <a class="dropdown-item bold" href="#">Ingeniería:</a>
    <a class="dropdown-item" href="#">Alimentaria</a>
    <a class="dropdown-item" href="#">Ambiental (Entidad a cargo: Gruntone)</a>
    <a class="dropdown-item" href="#">Agronómica</a>
    <a class="dropdown-item" href="#">Civil</a>
    <a class="dropdown-item" href="#">Eléctrica</a>
    <a class="dropdown-item" href="#">Mecatrónica</a>
    <a class="dropdown-item" href="#">Petróleo</a>
	<div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#">Medicina</a>
    <a class="dropdown-item" href="#">Mercadotecnia y Publicidad</a>
    <a class="dropdown-item" href="#">Pedagogía</a>
    <a class="dropdown-item" href="#">Psicología</a>
    <a class="dropdown-item" href="#">Relaciones Internacionales</a>
    <a class="dropdown-item" href="#">Sociología</a>
  </div>
</div>

<div class="contaner-fluid background-cover">
    <div class="row full-height justify-content-center align-items-center">
        <div class="col-xs-12 col-md-4 light-blue radius--25">
            <div class="">
				<div class="main-content">
					<h1 class="text-center text-white">Professional Support</h1>
					<p class="text-justify text-white-50">Desde 2017, Somos un equipo multidisciplinario de profesionales de todas las áreas y grados académicos enfocados en el coaching empresarial a nivel iberoamericano. 
                    Ofrecemos herramientas y aporte de profesionales para que su empresa prospere con eficiencia y eficacia.
                    </p>
				</div>
				<div id="logo">
				</div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-xs-12 col-md-12">
            <p class="text-center text-white top-space">           
                México | Guatemala | Costa Rica | Colombia | Perú
            </p>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.9.7/jquery.fullpage.min.js" integrity="sha512-bxzECOBohzcTcWocMAlNDE2kYs0QgwGs4eD8TlAN2vfovq13kfDfp95sJSZrNpt0VMkpP93ZxLC/+WN/7Trw2g==" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProfesionalSupport</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>